import jsPDF from "jspdf";
import * as XLSX from "xlsx";

// PDF Export utility
export function exportToPDF(
  title: string,
  headers: string[],
  data: (string | number)[][],
  summary?: { label: string; value: string }[]
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("BoutiqueOS", 14, 20);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("45, Pondy Bazaar, T. Nagar, Chennai 600017", 14, 28);
  doc.text("GSTIN: 33AABCU9603R1ZM", 14, 34);
  
  // Title
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(title, 14, 48);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated on: ${new Date().toLocaleString("en-IN")}`, 14, 56);
  
  let yPos = 66;
  
  // Summary section if provided
  if (summary && summary.length > 0) {
    doc.setFillColor(245, 245, 245);
    doc.rect(14, yPos, pageWidth - 28, summary.length * 8 + 8, "F");
    
    yPos += 6;
    summary.forEach((item) => {
      doc.setFont("helvetica", "normal");
      doc.text(item.label, 18, yPos + 4);
      doc.setFont("helvetica", "bold");
      doc.text(item.value, pageWidth - 50, yPos + 4);
      yPos += 8;
    });
    yPos += 10;
  }
  
  // Table header
  const colWidth = (pageWidth - 28) / headers.length;
  doc.setFillColor(30, 30, 30);
  doc.rect(14, yPos, pageWidth - 28, 10, "F");
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  headers.forEach((header, i) => {
    doc.text(header, 16 + i * colWidth, yPos + 7);
  });
  
  yPos += 10;
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "normal");
  
  // Table data
  data.forEach((row, rowIndex) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    
    if (rowIndex % 2 === 0) {
      doc.setFillColor(250, 250, 250);
      doc.rect(14, yPos, pageWidth - 28, 8, "F");
    }
    
    row.forEach((cell, i) => {
      const text = String(cell);
      doc.text(text.substring(0, 20), 16 + i * colWidth, yPos + 6);
    });
    yPos += 8;
  });
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${pageCount} | Generated by BoutiqueOS`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }
  
  doc.save(`${title.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.pdf`);
}

// Excel Export utility
export function exportToExcel(
  title: string,
  headers: string[],
  data: (string | number)[][],
  summary?: { label: string; value: string | number }[]
) {
  const workbook = XLSX.utils.book_new();
  
  // Create header row
  const wsData: (string | number)[][] = [];
  
  // Add title
  wsData.push([title]);
  wsData.push([`Generated on: ${new Date().toLocaleString("en-IN")}`]);
  wsData.push([]);
  
  // Add summary if provided
  if (summary && summary.length > 0) {
    summary.forEach((item) => {
      wsData.push([item.label, item.value]);
    });
    wsData.push([]);
  }
  
  // Add headers
  wsData.push(headers);
  
  // Add data
  data.forEach((row) => {
    wsData.push(row);
  });
  
  const worksheet = XLSX.utils.aoa_to_sheet(wsData);
  
  // Set column widths
  const colWidths = headers.map(() => ({ wch: 18 }));
  worksheet["!cols"] = colWidths;
  
  XLSX.utils.book_append_sheet(workbook, worksheet, "Report");
  
  XLSX.writeFile(workbook, `${title.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.xlsx`);
}

// Multi-sheet Excel export (each entry in sheets becomes its own tab)
export function exportToMultiSheetExcel(
  filename: string,
  sheets: {
    name: string;
    title: string;
    headers: string[];
    data: (string | number)[][];
    summary?: { label: string; value: string | number }[];
  }[]
) {
  const workbook = XLSX.utils.book_new();

  sheets.forEach((sheet) => {
    const wsData: (string | number)[][] = [];
    wsData.push([sheet.title]);
    wsData.push([`Generated on: ${new Date().toLocaleString("en-IN")}`]);
    wsData.push([]);

    if (sheet.summary && sheet.summary.length > 0) {
      sheet.summary.forEach((item) => wsData.push([item.label, item.value]));
      wsData.push([]);
    }

    wsData.push(sheet.headers);
    sheet.data.forEach((row) => wsData.push(row));

    const worksheet = XLSX.utils.aoa_to_sheet(wsData);
    worksheet["!cols"] = sheet.headers.map(() => ({ wch: 20 }));
    XLSX.utils.book_append_sheet(workbook, worksheet, sheet.name);
  });

  XLSX.writeFile(workbook, `${filename}_${new Date().toISOString().split("T")[0]}.xlsx`);
}

// Format currency for export
export function formatCurrencyForExport(amount: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}